//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doodle
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPackage
    {
        public int WPId { get; set; }
        public int DivisionId { get; set; }
        public string WPName { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<System.DateTime> ChangeControlSubmittedDate { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public Nullable<System.DateTime> PlannedStartDate { get; set; }
        public Nullable<System.DateTime> PlannedEndDate { get; set; }
        public Nullable<System.DateTime> EstimatedCompletionDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> PercentageComplete { get; set; }
        public string BusinessUser { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> Importance { get; set; }
        public Nullable<int> Urgency { get; set; }
        public Nullable<int> RapidyOfExcution { get; set; }
        public string Priority { get; set; }
        public Nullable<int> SubDivison { get; set; }
    }
}
